server:
  port: 8084

spring:
  kafka:
    streams:
      bootstrap-servers: localhost:29092
      application-id: kafka-streams

topic:
  create-client: create.client
  create-transaction: create.transaction